#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Enregistrer le chargeur automatique de Composer
require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

// Exécuter la console Artisan
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

// Terminer l'application et envoyer la réponse
$kernel->terminate($input, $status);

exit($status);
