#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| Enregistrement de l'autoloader Composer
|--------------------------------------------------------------------------
|
| Composer fournit un chargeur de classes pratique et automatique pour
| l'application. Nous devons simplement l'utiliser. Nous allons simplement
| l'exiger dans le script ici afin que nous n'ayons pas à nous soucier
| du chargement manuel des classes de l'application.
|
*/

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Exécution de l'application console Artisan
|--------------------------------------------------------------------------
|
| Lorsque nous exécutons l'application console, les commandes actuelles
| seront exécutées dans cette CLI et la réponse sera renvoyée au terminal.
|
*/

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

/*
|--------------------------------------------------------------------------
| Arrêt de l'application
|--------------------------------------------------------------------------
|
| Une fois qu'Artisan a terminé l'exécution, nous déclencherons les événements
| d'arrêt afin que tout travail final puisse être effectué par l'application
| avant de terminer le processus. C'est la dernière chose à faire.
|
*/

$kernel->terminate($input, $status);

exit($status);
